[package]
name = "web_scraping"
version = "0.1.0"
authors = ["Diego Castillo <raigiku@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thirtyfour = "0.11"
tokio = "0.2"
serde_json = "1.0"
serde = "1.0"